spring:
  boot:
     admin:
       client:
         url: http://localhost:8089
  application:
    name: spring-admin-client
    version: 1.0.0
# ??????
management:
  endpoints:
    web:
      exposure:
        # ????????????????*??????
        include: "*"
      # ????????????????
      base-path: /observe
  endpoint:
    health:
      # health ????? ??????????????????
      show-details: ALWAYS
    shutdown:
      # ????????????????????
      enabled: true
  info:
    env:
      # ??info?????????????info????
      enabled: true
# ???info?????info????????????
info:
  title: ${spring.application.name}
  version: ${spring.application.name}-${spring.application.version}
  description: ${spring.application.name}


